---
version: '3.7'
services:
  bot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: bash -c "go build -o cmd/discord-bot/discord-bot cmd/discord-bot/main.go && cmd/discord-bot/discord-bot"
    volumes:
      - .:/go/src/discord-bot
    tty: true
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
    ports:
      - 6380:6379
  musicbot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.music_bot
    command: bash -c "go build -o cmd/music-bot/music-bot cmd/music-bot/main.go && cmd/music-bot/music-bot"
    volumes:
      - .:/go/src/discord-bot
    tty: true
