name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod vendor

    - name: Run tests
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_LOG_CHANNEL_ID: ${{ secrets.BOT_LOG_CHANNEL_ID }}
        BOT_STOCK_CHANNEL_ID: ${{ secrets.BOT_STOCK_CHANNEL_ID }}
        MAINTAINERS: ${{ secrets.MAINTAINERS }}
        IEX_TEST_SECRET_TOKEN: ${{ secrets.IEX_TEST_SECRET_TOKEN }}
        IEX_TEST_PUBLISHABLE_TOKEN: ${{ secrets.IEX_TEST_PUBLISHABLE_TOKEN }}
        IEX_SECRET_TOKEN: ${{ secrets.IEX_SECRET_TOKEN }}
        IEX_PUBLISHABLE_TOKEN: ${{ secrets.IEX_PUBLISHABLE_TOKEN }}
        ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      run: make test
